POST http://localhost:4000/app/signup
Content-Type: application/json

{
    "fullName": "Last Test",
    "username": "lasttest",
    "email": "testing@lasttest.com",
    "password": "testlast1234456"
}